---
title: "Auteurs"
description: |
  Alle auteurs zijn verbonden aan de Hogeschool van Arnhem en Nijmegen.
---

## Witek ten Hove
Ik hou me graag bezig met vraagstukken op het gebied van data- en webtechnologieën. Mijn belangrijkste tools hiervoor zijn [R](https://www.rstudio.com/) en [JavaScript](https://www.w3schools.com/js/default.asp). Momenteel ligt mijn focus op het verdiepen van mijn skills op het gebied van [Node.js](https://nodejs.org/en/), [React](https://reactjs.org/) en NoSQL databases ([MongoDB](https://www.mongodb.com/) en [Google Firebase](https://firebase.google.com/)).

Ik heb bovendien het sterke vermoeden dat JavaScript zich naast Python en R zal gaan ontwikkelen tot een belangrijke taal voor Data Science. Aan die ontwikkeling wil ik actief deelnemen.

Overigens ben ik een enthousiaste supporter van de Open Source community. Al mijn werk mag daarom vrij worden gebruikt onder een [CC BY](https://creativecommons.org/licenses/by/4.0/) licentie en is beschikbaar via [Github](https://github.com/witusj).

## Humera Saeed
Een van mijn taken als International Relations Officer is het beheersen en verbeteren van uitgaande studentenmobiliteit. Iedere organisatie is op zoek naar manieren om de effectiviteit en/of de efficientie te verhogen. Ik ben anders tegen processen aan gaan kijken na het behalen van mijn Green Belt van World Class Performance Lean Six Sigma. Dit heeft mij geïnspireerd om onderdelen in mijn werk te ontdekken voor verbetering door middel van data-analyse.

Internationalisering is boeiend en het is interessant om mensen te leren kennen over de hele wereld. Het is mooi om te zien dat studenten elk jaar meer interesse tonen om naar het buitenland te gaan. Dit is voor mij een drijfveer om het proces zo goed mogelijk in te richten.

Wetenschap maakt mij nieuwsgierig en zet mij tot denken. Ik probeer nieuwe manieren te ontdekken en dit met mijn werk te combineren.

## Jeroen Veen
Ik heb 10 jaar ervaring met de projectleiding van multidisciplinaire (bio)medische projecten binnen de industrie en de zorgpraktijk en ben sinds 2014 aan de HAN verbonden. Mijn kennis en ervaring op het gebied van technologie tracht ik vooral in te zetten op projecten die een directe en zichtbare impact hebben op onze samenleving.

Naast onderzoeker en docent ben ik ook <a href="http://jeroenveen.nl/index.html" target="_blank">kunstenaar</a>. Met behulp van probabilistische computerprogramma's in combinatie met traditionele schilderkunst en experimentele patinatie probeer ik de worsteling met tijd en toeval te interpreteren.

